CYBER_KEYWORDS = [
    "cybersécurité",
    "cybersecurity",
    "security",
    "soc",
    "siem",
    "devsecops",
    "pentest",
    "blue team",
    "red team",
    "iam",
    "cloud security",
    "analyste sécurité",
    "rssi",
    "ingérieur réseau",
    "systèmes",
    "réseaux",
    "systèmes et réseaux",
    "helpdesk",
    "technicien",
]