CYBER_KEYWORDS = [
    # Core cybersecurity
    "cybersécurité",
    "cybersecurity",
    "cyber",
    "sécurité informatique",
    "sécurité des systèmes",
    "information security",
    # SOC / SIEM
    "soc",
    "siem",
    "analyste sécurité",
    "security analyst",
    "incident response",
    "threat intelligence",
    # Pentest / Red/Blue team
    "pentest",
    "penetration test",
    "red team",
    "blue team",
    "purple team",
    "ethical hacking",
    "ctf",
    # Domains
    "devsecops",
    "iam",
    "cloud security",
    "zero trust",
    "pki",
    "cryptographie",
    "forensic",
    "malware",
    "vulnerability",
    "firewall",
    "ids",
    "ips",
    # Network / infra (relevant for alternance)
    "réseaux",
    "systèmes et réseaux",
    "ingénieur réseau",
    "administrateur systèmes",
    "infrastructure",
    # GRC / compliance
    "rssi",
    "iso 27001",
    "rgpd",
    "gdpr",
    "conformité",
    "risk management",
    # Support / helpdesk (entry-level)
    "helpdesk",
    "technicien",
    # Companies
    "advens",
    "ovhcloud",
    "orange cyberdefense",
    "thales",
    "sopra steria",
    "capgemini",
    "stormshield",
    "claranet",
]
