version: '3.9'

services:
  backend:
    build: ./apps/backend
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app
    depends_on:
      - db

  frontend:
    build: ./apps/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobs
    ports:
      - "5432:5432"

  worker:
    build: ./apps/backend
    command: python worker/scheduler.py
    depends_on:
      - db
